on:
  push:
    branches:
      - development
      - release/alpha
      - release/alpha-*

permissions:
  contents: write
  pull-requests: write

name: release-please

jobs:
  release-please:
    runs-on: ubuntu-latest
    steps:
      - id: setup
        run: |
            SCRIPT='
                const e = /^release\/(?<name>\w+)/;
                const releaseName = e.exec(process.env.GITHUB_REF_NAME)?.groups?.name ?? "latest";
                console.log(`RELEASE_NAME=${JSON.stringify(releaseName)}`);
            '
            node -e $SCRIPT >> $GITHUB_OUTPUT
      - uses: google-github-actions/release-please-action@v3
        with:
          release-type: node
          prerelease: true
          monorepo-tags: true
          package-name: ${{ steps.setup.outputs.RELEASE_NAME }}
          default-branch: ${{ github.ref_name }}
          version-file: version

